# Generated by Django 4.0.4 on 2022-06-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='destino',
            field=models.CharField(choices=[('wareclouds', 'Wareclouds'), ('casamoda', 'CasaModa'), ('aura', 'Aura'), ('enviodirecto', 'EnvioDirecto'), ('otro', 'Otro')], max_length=20),
        ),
    ]
