# Generated by Django 4.0.4 on 2022-07-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['creado']},
        ),
    ]
