# Generated by Django 4.0.4 on 2022-06-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.proveedor'),
        ),
    ]
