# Generated by Django 4.0.4 on 2022-06-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_oficina',
            old_name='creado',
            new_name='actualizado',
        ),
    ]
