# Generated by Django 4.0.2 on 2022-06-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(blank=True, default='Otro', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sku', models.CharField(max_length=7)),
                ('destino', models.ManyToManyField(to='oficina.Destino')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sku', models.CharField(max_length=7)),
                ('proveedor', models.ManyToManyField(to='oficina.Proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
