# Generated by Django 4.0.4 on 2022-06-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_proveedor_nombre_salida_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='comentario',
            field=models.CharField(default='erer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salida',
            name='cantidad',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salida',
            name='comentario',
            field=models.CharField(default='qwe', max_length=200),
            preserve_default=False,
        ),
    ]
