# Generated by Django 4.0.4 on 2022-06-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_salida_destino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['sku']},
        ),
    ]
