# Generated by Django 4.0.4 on 2022-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_remove_catalogo_proveedor_catalogo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='comentario',
            field=models.CharField(blank=True, default='Comentario', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='sku',
            field=models.ManyToManyField(to='oficina.catalogo'),
        ),
    ]
