# Generated by Django 4.0.4 on 2022-06-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_alter_ingreso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['codigo', 'categoria', 'producto']},
        ),
    ]
