# Generated by Django 4.0.4 on 2022-06-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_alter_sku_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv_Of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True)),
                ('sku', models.CharField(max_length=7)),
                ('categoria', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=50)),
                ('ingresos', models.IntegerField()),
                ('salidas', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
