# Generated by Django 4.0.4 on 2022-07-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_remove_ingreso_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.proveedor'),
        ),
    ]
