# Generated by Django 4.0.4 on 2022-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_inventario_aura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_casa_moda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado', models.DateField(auto_now_add=True)),
                ('sku', models.CharField(max_length=7)),
                ('categoria', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=50)),
                ('ingresos', models.IntegerField()),
                ('salidas', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventario Casa Moda',
                'verbose_name_plural': 'Inventario Casa Moda',
            },
        ),
    ]
