# Generated by Django 4.0.4 on 2022-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0008_inventario_casa_moda'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_casa_moda',
            name='sucursal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
